<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-99P843S" failures="0" tests="5" name="com.villeos.Villeos_Web_app.NewTest" time="58.191" errors="1" timestamp="2023-08-20T17:31:50 IST" skipped="1">
  <testcase classname="com.villeos.Villeos_Web_app.NewTest" name="url" time="0.000">
    <skipped/>
  </testcase> <!-- url -->
  <testcase classname="com.villeos.Villeos_Web_app.NewTest" name="url" time="24.262"/>
  <testcase classname="com.villeos.Villeos_Web_app.NewTest" name="Setup" time="0.306">
    <error message="safaridriver located at C:\usr\bin\safaridriver, but invalid
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/
Build info: version: &#039;4.10.0&#039;, revision: &#039;c14d967899&#039;
System info: os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.6&#039;
Driver info: driver.version: SafariDriver" type="org.openqa.selenium.remote.NoSuchDriverException">
      <![CDATA[org.openqa.selenium.remote.NoSuchDriverException: safaridriver located at C:\usr\bin\safaridriver, but invalid
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: SafariDriver
at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:45)
at org.openqa.selenium.safari.SafariDriver.generateExecutor(SafariDriver.java:94)
at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:83)
at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:79)
at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:56)
at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:47)
at com.villeos.Villeos_Web_app.Base_class.Setup(Base_class.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:663)
at org.testng.TestRunner.beforeRun(TestRunner.java:652)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- Setup -->
  <testcase classname="com.villeos.Villeos_Web_app.NewTest" name="url" time="28.805"/>
  <testcase classname="com.villeos.Villeos_Web_app.NewTest" name="url" time="4.818"/>
</testsuite> <!-- com.villeos.Villeos_Web_app.NewTest -->
